apis/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from apis.views import CheckTaskStatus
from samples.views import BookViewSet
from stocks.views import (
    fetch_stock_history,
    get_stock_data,
    test,
    get_all_stock_data_by_data_range,
    get_last_trading_date,
)

router = DefaultRouter()
router.register(r"books", BookViewSet)

urlpatterns = [
    path("", include(router.urls)),
    path("fetch_stock_history/", fetch_stock_history, name="fetch_stock_history"),
    # 根据日期区间获取股票的数据
    path(
        "stock/date_range/",
        get_all_stock_data_by_data_range,
        name="get_all_stock_data_by_data_range",
    ),
    # 根据股票数据的最后一个交易日
    path(
        "stock/last_trading_date/", get_last_trading_date, name="get_last_trading_date"
    ),
    # 获取特定股票的数据
    path("stock/<str:stock_code>/", get_stock_data, name="get_stock_data"),
    path("test", test, name="test"),
    path(
        "check_task/<str:task_id>/",
        CheckTaskStatus.as_view(),
        name="check_task_status",
    ),
]

samples/urls.py
from django.urls import path

from . import views

app_name = "samples"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

x_data/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("api/", include("apis.urls")),
    path("samples/", include("samples.urls")),
    path("admin/", admin.site.urls),
]

samples/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    published_date = models.DateField()

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['title', 'author'], name='unique_title_author')
        ]

    def __str__(self):
        return self.title

samples/views.py
from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from rest_framework import viewsets
from .serializers import BookSerializer

from .models import Choice, Question, Book


class IndexView(generic.ListView):
    template_name = "samples/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "samples/detail.html"


class ResultsView(generic.DetailView):
    model = Question
    template_name = "samples/results.html"


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "samples/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("samples:results", args=(question.id,)))


class BookViewSet(viewsets.ModelViewSet):
    queryset = Book.objects.all()
    serializer_class = BookSerializer

templates/samples/detail.html
<form action="{% url 'samples:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

templates/samples/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'samples/style.css' %}">
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'samples:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No samples are available.</p>
{% endif %}

templates/samples/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'samples:detail' question.id %}">Vote again?</a>